r"""Table — twin-experiment parameter recovery (LaTeX), generated from the frozen seed-ensemble CSV.

Best-of-20 signed relative error (%) of each recovered parameter against its synthetic-observation
reference, per experiment (MERGED + six stations), plus the achieved cost (mean-normalised NRMSE).
Each cell is shaded red with an intensity that grows with |error|, so the equifinal cells (warm-station
recruitment, HOT mortality) stand out while the recovered cells stay white. This is the typeset-table
counterpart of Figure 8's recovery heatmap, reusing the exact same product and reference values
(figstyle.REF / PLABEL / order / label) so the numbers match the figure.

The shaded cells use \cellcolor, so the manuscript preamble needs \usepackage[table]{xcolor}.

Emits the tabular ONLY, so it can be \input inside a table* float whose \caption is written in the
manuscript (the numbers regenerate here, the wording stays under the author's control). A ready-made
table* + caption wrapper is printed to stdout for convenience.

Reads ONLY products/cmaes_seed_ensemble_l{lam}{metric}.csv (same product as fig08_recovery.py).
Output : products/recovery_table.tex   (the tabular, to \input; also printed to stdout)
Run    : .venv/bin/python scripts/tables/build_recovery_table.py [--metric nrmse_mean]
"""
from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from seapopym_repro import figstyle as fs, paths

ap = argparse.ArgumentParser()
ap.add_argument("--metric", default=paths.PRODUCTION_METRIC, help="cost metric whose frozen run to tabulate")
METRIC = ap.parse_args().metric

d = pd.read_csv(paths.cmaes_product("seed_ensemble", METRIC))
EXP = fs.order(set(d.experiment))                                        # MERGED + present stations, canonical order
best = d.loc[d.groupby("experiment").best_nrmse.idxmin().values].set_index("experiment")   # best seed / experiment
nrmse_min = d.groupby("experiment").best_nrmse.min()                     # achieved cost of that best restart

# Discrete red shading vs |relative error| (%), mirroring Figure 8's colour bounds, capped at red!50
# so the black cell text stays readable. Recovered cells (|error| < 1 %) get no shading.
SHADE = [(1, 0), (10, 12), (25, 25), (50, 38)]


def relerr(value, p: str) -> float:
    return (float(value) - fs.REF[p]) / abs(fs.REF[p]) * 100.0


def fmt_err(e: float) -> str:
    if round(e, 1) == 0:                     # within +/-0.05 %: recovered, print a plain 0 (as in the figure)
        return "0"
    return f"{e:+.0f}" if abs(e) >= 10 else f"{e:+.1f}"


def shade_level(abserr: float) -> int:
    for thr, lvl in SHADE:
        if abserr < thr:
            return lvl
    return 50


def cell(value, p: str) -> str:
    e = relerr(value, p)
    txt = f"${fmt_err(e)}$"
    lvl = shade_level(abs(e))
    return txt if lvl == 0 else rf"\cellcolor{{red!{lvl}}}{txt}"


def sci(v: float) -> str:
    ex = int(np.floor(np.log10(v)))
    return rf"${v / 10 ** ex:.1f}\times10^{{{ex}}}$"


# Only the tabular is generated, so it can be \input inside a table* float whose \caption lives in
# the manuscript (the numbers regenerate here, the wording stays under the author's control).
lines = [
    r"% Auto-generated by scripts/tables/build_recovery_table.py from the frozen seed-ensemble CSV.",
    r"% Do not edit by hand. \input this inside a table* float and write the \caption in the manuscript.",
    r"% Coloured cells need \usepackage{colortbl} (or \PassOptionsToPackage{table}{xcolor} before \documentclass).",
    r"\begin{tabular}{@{}l rrrrr r@{}}",
    r"\toprule",
    r"Synthetic observation & " + " & ".join(fs.PLABEL[p] for p in fs.PARAM_ORDER) + r" & NRMSE$_\mathrm{mean}$\\",
    r"(station) & " + " & ".join(f"${fs.REF[p]:g}$" for p in fs.PARAM_ORDER) + r" & \\",
    r"\midrule",
]
for e in EXP:
    cells = " & ".join(cell(best.loc[e, p], p) for p in fs.PARAM_ORDER)
    lines.append(f"{fs.label(e)} & {cells} & {sci(float(nrmse_min[e]))}" + r"\\")
lines += [r"\bottomrule", r"\end{tabular}"]

tex = "\n".join(lines) + "\n"
out = paths.PRODUCTS / "recovery_table.tex"
out.write_text(tex)
print(tex)
print(f"wrote {out}\n")

# Suggested manuscript wrapper (printed only, not written): adjust the caption wording as you like.
CAPTION = (
    r"Parameter recovery in the twin experiments, from the best of twenty CMA-ES restarts. Each entry "
    r"is the signed relative error of a recovered parameter against its synthetic-observation reference, "
    r"in percent, $(\hat{\theta}-\theta)/|\theta|\times100$. The last column is the achieved cost "
    r"(mean-normalised NRMSE). Cell shading grows with the absolute error. The cold stations and MERGED "
    r"recover all five parameters, CANARY and BATS miss the two recruitment parameters, and HOT does not "
    r"reach the optimum. A large error next to a near-zero cost is equifinality."
)
print("% ---- suggested manuscript wrapper (write/adjust the caption here) ----")
print(r"% \begin{table*}[t]")
print(r"% \caption{" + CAPTION + r"}")
print(r"% \label{tab:recovery}")
print(r"% \input{recovery_table.tex}")
print(r"% \end{table*}")
