r"""Table — twin-experiment parameter recovery (LaTeX), generated from the frozen seed-ensemble CSV.

Best-of-20 signed relative error (%) of each recovered parameter against its synthetic-observation
reference, per experiment (MERGED + six stations), plus the achieved cost (mean-normalised NRMSE).
The equifinal cells (a large error next to a near-zero cost) are read from the numbers alone, with no
cell shading, so the table stays neutral and does not pre-judge which cells are failures. This is the
typeset-table counterpart of Figure 8's recovery heatmap, reusing the exact same product and reference
values (figstyle.REF / PLABEL / order / label) so the numbers match the figure.

Emits the tabular ONLY, so it can be \input inside a table* float whose \caption is written in the
manuscript (the numbers regenerate here, the wording stays under the author's control). A ready-made
table* + caption wrapper is printed to stdout for convenience.

Reads ONLY products/cmaes_seed_ensemble_l{lam}{metric}.csv (same product as fig08_recovery.py).
Output : products/recovery_table.tex   (the tabular, to \input; also printed to stdout)
Run    : .venv/bin/python scripts/tables/build_recovery_table.py [--metric nrmse_mean]
"""
from __future__ import annotations

import argparse

import numpy as np
import pandas as pd

from seapopym_repro import figstyle as fs, paths

ap = argparse.ArgumentParser()
ap.add_argument("--metric", default=paths.PRODUCTION_METRIC, help="cost metric whose frozen run to tabulate")
METRIC = ap.parse_args().metric

d = pd.read_csv(paths.cmaes_product("seed_ensemble", METRIC))
EXP = fs.order(set(d.experiment))                                        # MERGED + present stations, canonical order
best = d.loc[d.groupby("experiment").best_nrmse.idxmin().values].set_index("experiment")   # best seed / experiment
nrmse_min = d.groupby("experiment").best_nrmse.min()                     # achieved cost of that best restart

def relerr(value, p: str) -> float:
    return (float(value) - fs.REF[p]) / abs(fs.REF[p]) * 100.0


def fmt_err(e: float) -> str:
    if round(e, 1) == 0:                     # within +/-0.05 %: recovered, print a plain 0 (as in the figure)
        return "0"
    return f"{e:+.0f}" if abs(e) >= 10 else f"{e:+.1f}"


def cell(value, p: str) -> str:
    return f"${fmt_err(relerr(value, p))}$"


def sci(v: float) -> str:
    ex = int(np.floor(np.log10(v)))
    return rf"${v / 10 ** ex:.1f}\times10^{{{ex}}}$"


# Only the tabular is generated, so it can be \input inside a table* float whose \caption lives in
# the manuscript (the numbers regenerate here, the wording stays under the author's control).
lines = [
    r"% Auto-generated by scripts/tables/build_recovery_table.py from the frozen seed-ensemble CSV.",
    r"% Do not edit by hand. \input this inside a table* float and write the \caption in the manuscript.",
    r"\begin{tabular}{@{}l rrrrr r@{}}",
    r"\toprule",
    r"Synthetic observation & " + " & ".join(fs.PLABEL[p] for p in fs.PARAM_ORDER) + r" & NRMSE\\",
    r"(station) & " + " & ".join(f"${fs.REF[p]:g}$" for p in fs.PARAM_ORDER) + r" & \\",
    r"\midrule",
]
for e in EXP:
    cells = " & ".join(cell(best.loc[e, p], p) for p in fs.PARAM_ORDER)
    lines.append(f"{fs.label(e)} & {cells} & {sci(float(nrmse_min[e]))}" + r"\\")
lines += [r"\bottomrule", r"\end{tabular}"]

tex = "\n".join(lines) + "\n"
out = paths.PRODUCTS / "recovery_table.tex"
out.write_text(tex)
print(tex)
print(f"wrote {out}\n")

# Suggested manuscript wrapper (printed only, not written): adjust the caption wording as you like.
CAPTION = (
    r"Parameter recovery in the twin experiments, from the best of twenty CMA-ES restarts. Each entry "
    r"is the signed relative error of a recovered parameter against its synthetic-observation reference, "
    r"in percent, $(\hat{\theta}-\theta)/|\theta|\times100$. The last column is the achieved cost "
    r"(mean-normalised NRMSE). The cold stations and MERGED "
    r"recover all five parameters, CANARY and BATS miss the two recruitment parameters, and HOT does not "
    r"reach the optimum. A large error next to a near-zero cost is equifinality."
)
print("% ---- suggested manuscript wrapper (write/adjust the caption here) ----")
print(r"% \begin{table*}[t]")
print(r"% \caption{" + CAPTION + r"}")
print(r"% \label{tab:recovery}")
print(r"% \input{recovery_table.tex}")
print(r"% \end{table*}")
